### ISSUE TITLE
Add "Trading APY" to our overall APY per vault. ($500 UI + $2000 API Bounty)

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#244]
This is a feature that I've been meaning to add for some time, and I just saw that Alpha Homora has it implemented.

They display the trading APY of holding an LP and add it to the total as well. This is relevant because a lot of the time, you're comparing the profitability of farming with an LP as opposed to holding an asset like BNB. In this sense, the trading profits are part of the equation, and it would be good to be explicit about it.

**Comment by roman-monk** [comment]
Blocked by API task: https://github.com/beefyfinance/beefy-api/issues/111

**Comment by nienow** [comment]
Since pancake info data is outdated, we should have a warning, like Alpha has: "Trading fees APR shown has only synced to block number 5640759/6706829. The data shown may be delayed and not reflect the actual APR." Or we simply wait until pancake data is fixed to show their trading data, since it can be misleading.

**Comment by akiraplusplus** [comment]
Hi, Can you assign me this issue to me?

**Comment by sirbeefalot** [comment]
> Hi, Can you assign me this issue to me?

Of course 😄

**Comment by akiraplusplus** [comment]
@sirbeefalot - Are you available for a short video call, and explain the ticket in detail?
