### ISSUE TITLE
Improve the way we display TVL and APY numbers. 

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-app#49]
Right now we're using somewhat of a confusing nomenclature for APYs 

Something like 1.15k% is used for example instead of 1150% which would take up the same space but be clearer. 

On the TVL side, something like $141.01k takes up the same space than $141,000 and is less clear too. 

Revamping this could diminish confusion from newbies and increase retention

**Comment by superbeefyboy** [comment]
There is an important detail tho. With the current implementation the format is always consistent.

Given a 'dimension', the significant number goes from 1 to 999, and then it jumps to the next unit.
In order to make a special case for 1xxx, we might need to add some ugly edge case to the code.

We could re-implement the function, if there is a better definition of the supported cases.
The current format fn always shows 2 decimals, and up to 3 significant digits of the given unit.

$141.01k uses the horizontal than $141,000, but this doesn't work with $3.17M for example.
(this 'problem' only affects TVL. APYs are normally under the 5 digits these days)

**Comment by sirbeefalot** [comment]
It seems like we'll leave them as they are for now.
